# Build settings
permalink   : /blog/:year/:title/
markdown    : kramdown

paginate: 3
paginate_path: "/blog/page/:num/"
comments: true

destination: _site
sass:
  sass_dir: _scss
  style: compressed # expanded

# SEO settings
title: Javier López - Software Engineer
description: "Javier López - Software Engineer: PHP, Java, Scala, Elasticsearch, Docker."
keywords: "software, engineer, php, java, scala, elasticsearch, docker"
url: http://loalf.github.io

# google_analytics: UA-52446115-1
repo: http://github.com/loalf
disqus_shortname: "loalf"
disqus_site_shortname: "loalf"

# Author settings
author:
  name      : Javier López
  job       : Software Engineer
  bio       : "I am passionate, creative and enthusiastic software engineer, always eager to learn and experiment with new technologies."
  thumb     : /images/avatar.jpg
  email     : alcaraz1983@gmail.com
  url       : http://loalf.github.io
  github    : http://github.com/loalf
  twitter   : http://twitter.com/loalf
  linkedin  : http://linkedin.com/in/loalf

# navbar pages
navbar:
  - slug: about
    title: About
  - slug: talks
    title: Talks
  # - slug: skills
  #   title: Skills
  - slug: blog
    title: Blog

gems: [jekyll-paginate]